### PR TITLE
Create google analytics look/feel for ui

### PR DESCRIPTION
**Pull request by sebworks**
Closes issue #5

### CODE REVIEW

**Comment by anselmbradford** [comment]
Someone's been busy this morning! Good stuff.

**Comment by ascott1** [comment]
Nice!

**Comment by Ooblioob** [comment]
Very nice, no complaints here.  I'm gonna try it out and let you know how it goes...

**Comment by Ooblioob** [comment]
Yep, this looks great!  Prepare to merge!

**Pull request merged**
